name: Clavid Pull Request Reviewer
description: A GitHub Action that reviews pull requests
author: samdouble

inputs:
  anthropic_api_key:
    description: An Anthropic API key
    required: false
  additional_instructions:
    description: Additional instructions for the review
    required: false
  github_token:
    description: A GitHub token
    required: false

branding:
  icon: activity
  color: green

runs:
  using: node20
  main: index.js
